name: belajar_dart_package_library
description: A starting point for Dart libraries or applications.
version: 1.5.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-85.0.dev <4.0.0'

publish_to: none # must publish to none if using git
# Add regular dependencies here.
dependencies:
  Library_Dart:
    git:
      url: git@github.com:Muhammadreztu87/Library-Dart.git
      ref: 1.5.0 #branch or tag

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
